In [4]:
#all the librarys used in this project
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib

In [5]:
data = pd.read_excel('MUSB Hackathon.xlsx')

In [6]:
data.head()

Customer ID      Date of Default  Amount Default  \
0    546301568  2019-08-24 00:00:00          582993   
1     18658241  2020-12-04 00:00:00          760344   
2    545307255  2018-10-30 00:00:00          433971   
3    685777392  2019-04-14 00:00:00          945476   
4    838154128  2020-11-30 00:00:00          874825   

   Cumulative Payment till date  Total Loan  Gender  State   Bank  Default  \
0                      420324.0   1003317.0       1      0  ICICI        1   
1                      708671.0   1469015.0       1      0    SBI        1   
2                      835055.0   1269026.0       0      2    SBI        0   
3                      759583.0   1705059.0       0      1    SBI        1   
4                       71394.0    946219.0       1      2    SBI        1   

   Purchase Channel   Age  Insurance    Loan  Savings  FD  DMAT Fraud  \
0                 3  59.0          1  663918   216348   0     1     N   
1                 1  59.0          1  107236   439609   1     0     N   
2                 1  35.0          0  745659   415287   1     0     N   
3                 2  38.0          0   24216   284974   0     0     N   
4                 3  50.0          0  794057    18748   1     1     N   

   Card Type     City  
0          0    Delhi  
1          0  Kolkata  
2          1    Delhi  
3          0   Mumbai  
4          1   Mumbai

In [7]:
data.columns # column names

Index(['Customer ID', 'Date of Default', 'Amount Default',
       'Cumulative Payment till date', 'Total Loan', 'Gender', 'State', 'Bank',
       'Default', 'Purchase Channel', 'Age', 'Insurance', 'Loan', 'Savings',
       'FD', 'DMAT', 'Fraud', 'Card Type', 'City'],
      dtype='object')

In [8]:
data.isnull().sum()

Customer ID                     0
Date of Default                 0
Amount Default                  0
Cumulative Payment till date    1
Total Loan                      1
Gender                          0
State                           0
Bank                            0
Default                         0
Purchase Channel                0
Age                             1
Insurance                       0
Loan                            0
Savings                         0
FD                              0
DMAT                            0
Fraud                           0
Card Type                       0
City                            0
dtype: int64

## Data Cleanig 

In [9]:
data.dropna(how='any', inplace= True) #since only two of the columns contain null value of 1 each droping 2 rows 
#would not have much impact given the amount of data

In [18]:
#renaming the columns
data = data.rename(columns={'Cumulative Payment till date': "Repayed"})

In [10]:
data.drop(['Loan', 'State', 'Customer ID', 'Date of Default'], axis=1, inplace = True)

In [11]:
data.columns

Index(['Amount Default', 'Cumulative Payment till date', 'Total Loan',
       'Gender', 'Bank', 'Default', 'Purchase Channel', 'Age', 'Insurance',
       'Savings', 'FD', 'DMAT', 'Fraud', 'Card Type', 'City'],
      dtype='object')

In [12]:
data.groupby('Default')['Gender'].count()

Default
0    5020
1    4978
Name: Gender, dtype: int64

In [13]:
data.groupby('City')['Default'].sum()

City
Chennai    1290
Delhi      1258
Kolkata    1197
Mumbai     1233
Name: Default, dtype: int64

In [14]:
data.groupby('Default')['Insurance'].sum()

Default
0    2533
1    2445
Name: Insurance, dtype: int64

In [15]:
data.groupby('Bank')['Default'].sum()

Bank
HDFC     1680
ICICI    1634
SBI      1664
Name: Default, dtype: int64

## X and Y variables for y = default

In [16]:
data.shape

(9998, 15)

In [19]:
X = data[['Amount Default', 'Repayed', 'Total Loan', 'Gender', 'Bank',
       'Purchase Channel', 'Age', 'Insurance', 'Savings', 'FD', 'DMAT',
       'Fraud', 'Card Type', 'City']].values

In [20]:
X.shape

(9998, 14)

In [21]:
y = data[['Default']].values

In [22]:
type(y)

numpy.ndarray

In [ ]:
#columns which needs one hot encoding and label encoding
#Bank, City and Fraud

In [ ]:
data.head()

In [ ]:
X[:,11]

In [23]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:,4] = labelencoder.fit_transform(X[:,4])
X[:,11] = labelencoder.fit_transform(X[:,11])
X[:,13] = labelencoder.fit_transform(X[:,13])

In [24]:
X

array([[582993, 420324.0, 1003317.0, ..., 0, 0, 1],
       [760344, 708671.0, 1469015.0, ..., 0, 0, 2],
       [433971, 835055.0, 1269026.0, ..., 0, 1, 1],
       ...,
       [634376, 723328.0, 1357704.0, ..., 0, 1, 3],
       [160692, 844678.0, 1005370.0, ..., 0, 1, 3],
       [654997, 726110.0, 1381107.0, ..., 0, 1, 2]], dtype=object)

In [25]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Bank", OneHotEncoder(), [4])], remainder= 'passthrough')
X = ct.fit_transform(X)
X

array([[0.0, 1.0, 0.0, ..., 0, 0, 1],
       [0.0, 0.0, 1.0, ..., 0, 0, 2],
       [0.0, 0.0, 1.0, ..., 0, 1, 1],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 1, 3],
       [0.0, 0.0, 1.0, ..., 0, 1, 3],
       [1.0, 0.0, 0.0, ..., 0, 1, 2]], dtype=object)

In [ ]:
X[[1]]

In [26]:

ct = ColumnTransformer([("City", OneHotEncoder(), [15])], remainder= 'passthrough')
X = ct.fit_transform(X)

In [27]:
X.shape

(9998, 19)

In [28]:
X = pd.DataFrame(X, columns =["C1","C2", "C3","C4", "B1", "B2", "B3", 'Amount Default', 'Repayed', 'Total Loan', 'Gender',
       'Purchase Channel', 'Age', 'Insurance', 'Savings', 'FD', 'DMAT',
       'Fraud', 'Card Type'])

In [29]:
X.head()

C1 C2 C3 C4 B1 B2 B3 Amount Default Repayed   Total Loan Gender  \
0  0  1  0  0  0  1  0         582993  420324  1.00332e+06      1   
1  0  0  1  0  0  0  1         760344  708671  1.46902e+06      1   
2  0  1  0  0  0  0  1         433971  835055  1.26903e+06      0   
3  0  0  0  1  0  0  1         945476  759583  1.70506e+06      0   
4  0  0  0  1  0  0  1         874825   71394       946219      1   

  Purchase Channel Age Insurance Savings FD DMAT Fraud Card Type  
0                3  59         1  216348  0    1     0         0  
1                1  59         1  439609  1    0     0         0  
2                1  35         0  415287  1    0     0         1  
3                2  38         0  284974  0    0     0         0  
4                3  50         0   18748  1    1     0         1

In [30]:
X.drop(columns=["B1", "C1"], axis = 1, inplace = True)

In [31]:
X.head()

C2 C3 C4 B2 B3 Amount Default Repayed   Total Loan Gender Purchase Channel  \
0  1  0  0  1  0         582993  420324  1.00332e+06      1                3   
1  0  1  0  0  1         760344  708671  1.46902e+06      1                1   
2  1  0  0  0  1         433971  835055  1.26903e+06      0                1   
3  0  0  1  0  1         945476  759583  1.70506e+06      0                2   
4  0  0  1  0  1         874825   71394       946219      1                3   

  Age Insurance Savings FD DMAT Fraud Card Type  
0  59         1  216348  0    1     0         0  
1  59         1  439609  1    0     0         0  
2  35         0  415287  1    0     0         1  
3  38         0  284974  0    0     0         0  
4  50         0   18748  1    1     0         1

## Train test split 

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state = 0)

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train  = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [34]:
X.shape

(9998, 17)

In [35]:
y.shape

(9998, 1)

In [36]:
y

array([[1],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [37]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense


def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 9, kernel_initializer = 'uniform', activation ='relu', input_dim = 17))
    classifier.add(Dense(units = 9, kernel_initializer = 'uniform', activation ='relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation ='sigmoid'))
    classifier.compile(optimizer = 'adam', loss= 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier 

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs =100)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = 1)
mean = accuracies.mean()
variance = accuracies.std()

ImportError: cannot import name '__internal__' from 'tensorflow._api.v2' (C:\Users\ashte\anaconda3\lib\site-packages\tensorflow\_api\v2\__init__.py)

In [ ]:
!pip3 uninstall keras-nightly
!pip3 uninstall -y tensorflow
!pip3 install keras==2.1.6
!pip3 install tensorflow==1.15.0
!pip3 install h5py==2.10.0

In [ ]:
X['Score'] = 

In [3]:
!pip3 install tensorflow==1.13.0

ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.0 (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0)
ERROR: No matching distribution found for tensorflow==1.13.0
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.


In [39]:
pip3 install upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.13.0-py3-none-any.whl

SyntaxError: invalid syntax (<ipython-input-39-7270f2db64f1>, line 1)

In [40]:
data.dtypes

Amount Default        int64
Repayed             float64
Total Loan          float64
Gender                int64
Bank                 object
Default               int64
Purchase Channel      int64
Age                 float64
Insurance             int64
Savings               int64
FD                    int64
DMAT                  int64
Fraud                object
Card Type             int64
City                 object
dtype: object